# Generated by Django 5.0.6 on 2024-05-28 16:01

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

# SQL để tạo unaccent dictionary nếu nó chưa được tự động tạo bởi extension
# Extension unaccent cung cấp template 'unaccent'
CREATE_UNACCENT_DICTIONARY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_ts_dict WHERE dictname = 'unaccent_dict'
    ) THEN
        CREATE TEXT SEARCH DICTIONARY unaccent_dict (
            TEMPLATE = unaccent,
            RULES = 'unaccent' -- Hoặc để trống nếu không có file rules cụ thể
        );
    END IF;
END
$$;
"""

# SQL để xóa dictionary (nếu cần rollback)
DROP_UNACCENT_DICTIONARY_SQL = """
DROP TEXT SEARCH DICTIONARY IF EXISTS unaccent_dict;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
        migrations.RunSQL(
            CREATE_UNACCENT_DICTIONARY_SQL,
            DROP_UNACCENT_DICTIONARY_SQL
        ),
    ]
