# Generated by Django 5.0.6 on 2024-05-28 16:05

from django.db import migrations

CREATE_VIETNAMESE_FTS_CONFIGURATION_STEP1 = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM   pg_catalog.pg_ts_config
        WHERE  cfgname = 'vietnamese'
    ) THEN
        CREATE TEXT SEARCH CONFIGURATION vietnamese (COPY = simple);
    END IF;
END
$$;
"""

DROP_VIETNAMESE_FTS_CONFIGURATION = """
DROP TEXT SEARCH CONFIGURATION IF EXISTS vietnamese;
"""


class Migration(migrations.Migration):

    dependencies = [
        # Phụ thuộc vào migration trước
        ('summarizer', '0002_create_unaccent_extension'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_VIETNAMESE_FTS_CONFIGURATION_STEP1,
            DROP_VIETNAMESE_FTS_CONFIGURATION
        ),
    ]
