# Generated by Django 5.0.6 on 2024-05-29 00:00

from django.db import migrations

ALTER_VIETNAMESE_FTS_CONFIGURATION_STEP2 = """
DO $$
BEGIN
    -- Chỉ thực hiện nếu FTS config 'vietnamese' đã tồn tại
    IF EXISTS (
        SELECT 1
        FROM   pg_catalog.pg_ts_config
        WHERE  cfgname = 'vietnamese'
    ) THEN
        ALTER TEXT SEARCH CONFIGURATION vietnamese
            ALTER MAPPING FOR hword, hword_part, word
            WITH unaccent_dict, simple;
    END IF;
END
$$;
"""

# Lệnh rollback sẽ phức tạp hơn, vì khó biết trạng thái trước đó là gì.
# Tạm thời có thể không làm gì, hoặc drop và recreate lại từ 'simple' nếu cần rollback kỹ.
# Ở đây, để đơn giản, lệnh rollback sẽ không làm gì cụ thể với unaccent.
REVERSE_ALTER_VIETNAMESE_FTS_CONFIGURATION_STEP2 = migrations.RunSQL.noop


class Migration(migrations.Migration):

    dependencies = [
        # Phụ thuộc vào migration 0003
        ('summarizer', '0003_create_vietnamese_fts_config'),
    ]

    operations = [
        migrations.RunSQL(
            ALTER_VIETNAMESE_FTS_CONFIGURATION_STEP2,
            REVERSE_ALTER_VIETNAMESE_FTS_CONFIGURATION_STEP2
        ),
    ]
