# Generated by Django 5.1.6 on 2025-05-14 06:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryClickLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('summary_id', models.UUIDField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'summary_id'], name='recommender_user_id_0a6b5b_idx'), models.Index(fields=['clicked_at'], name='recommender_clicked_917184_idx'), models.Index(fields=['created_at'], name='recommender_created_f2b375_idx')],
            },
        ),
        migrations.CreateModel(
            name='SummaryRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('category_score', models.FloatField(default=0.0)),
                ('search_history_score', models.FloatField(default=0.0)),
                ('favorite_keywords_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'total_score'], name='recommender_user_id_7bd770_idx'), models.Index(fields=['summary_id', 'user_id'], name='recommender_summary_ddca90_idx')],
                'unique_together': {('summary_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='SummaryViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('summary_id', models.UUIDField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summary View Log',
                'verbose_name_plural': 'Summary View Logs',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user_id', 'summary_id'], name='recommender_user_id_67f898_idx'), models.Index(fields=['viewed_at'], name='recommender_viewed__153d59_idx'), models.Index(fields=['created_at'], name='recommender_created_643631_idx')],
            },
        ),
    ]
