# Generated by Django 5.1.6 on 2025-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_summaryviewlog_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryclicklog',
            name='user_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='summaryviewlog',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
