# Generated by Django 5.1.6 on 2025-04-09 16:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssummary',
            options={
                'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newssummary',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True,
                editable=False,
                null=True),
        ),
        migrations.AddIndex(
            model_name='newssummary',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='news_newssu_search__48e9a4_gin'),
        ),
    ]
