# Generated by Django 5.1.6 on 2025-04-09 16:41

from django.db import migrations

class Migration(migrations.Migration):

    # Thêm dependencies nếu cần, ví dụ: phụ thuộc vào migration tạo bảng NewsSummary
    dependencies = [
        ('news', '0003_alter_newssummary_options_newssummary_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Tạo extension unaccent nếu chưa có
            CREATE EXTENSION IF NOT EXISTS unaccent;
            -- Tạo cấu hình text search 'vietnamese' dựa trên 'simple'
            CREATE TEXT SEARCH CONFIGURATION public.vietnamese ( COPY = pg_catalog.simple );
            -- Chỉ định sử dụng unaccent và simple cho các loại token
            -- (Bạn có thể điều chỉnh danh sách token nếu cần)
            ALTER TEXT SEARCH CONFIGURATION public.vietnamese
                ALTER MAPPING FOR hword, hword_part, word, asciiword, asciihword
                WITH unaccent, simple;
            """,
            # Lệnh để hoàn tác khi migrate về phiên bản trước đó
            reverse_sql="""
            DROP TEXT SEARCH CONFIGURATION IF EXISTS public.vietnamese;
            -- Không nên DROP EXTENSION unaccent ở đây nếu nó có thể được dùng bởi thứ khác
            -- Chỉ drop nếu bạn chắc chắn nó chỉ dùng cho config này
            -- DROP EXTENSION IF EXISTS unaccent;
            """
            # Lưu ý: Sử dụng `public.vietnamese` để rõ ràng về schema
        ),
    ]
