# Generated by Django 5.1.6 on 2025-05-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_setup_fts_vietnamese'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingNews',
        ),
    ]
